### ISSUE TITLE
crash: Double tap to swap camera crashes app

### ISSUE THREAD

**Issue by deekoder** [minio/alice#103]
```
FATAL EXCEPTION: main
                                                                    Process: com.minio.io.alice, PID: 19839
                                                                    java.lang.IllegalThreadStateException: Thread already started
                                                                        at java.lang.Thread.checkNotStarted(Thread.java:849)
                                                                        at java.lang.Thread.start(Thread.java:1059)
                                                                        at com.minio.io.alice.CameraSourcePreview.startIfReady(CameraSourcePreview.java:117)
                                                                        at com.minio.io.alice.CameraSourcePreview.start(CameraSourcePreview.java:78)
                                                                        at com.minio.io.alice.CameraSourcePreview.start(CameraSourcePreview.java:84)
                                                                        at com.minio.io.alice.MainActivity.startPreview(MainActivity.java:291)
                                                                        at com.minio.io.alice.CameraDeviceManager.startCameraSource(CameraDeviceManager.java:122)
                                                                        at com.minio.io.alice.CameraDeviceManager.swapCameraSource(CameraDeviceManager.java:146)
                                                                        at com.minio.io.alice.MainActivity.swapCamera(MainActivity.java:275)
                                                                        at com.minio.io.alice.MainActivity$GestureListener.onDoubleTap(MainActivity.java:255)
                                                                        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:576)
                                                                        at com.minio.io.alice.MainActivity.onTouchEvent(MainActivity.java:109)
                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:3049)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2777)
                                                                        at android.view.View.dispatchPointerEvent(View.java:10233)
```

**Comment by poornas** [comment]
closed per #109
