### ISSUE TITLE
crash: Zooming camera properties crashes

### ISSUE THREAD

**Issue by harshavardhana** [minio/alice#104]
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
                                                                        at com.minio.io.alice.CameraSourcePreview$1.onProgressChanged(CameraSourcePreview.java:246)
                                                                        at android.widget.SeekBar.onProgressRefresh(SeekBar.java:93)
                                                                        at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1390)
                                                                        at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1406)
                                                                        at android.widget.ProgressBar.setProgress(ProgressBar.java:1452)
                                                                        at android.widget.AbsSeekBar.setProgress(AbsSeekBar.java:1261)
                                                                        at android.widget.ProgressBar.setProgress(ProgressBar.java:1434)
                                                                        at android.widget.ProgressBar.incrementProgressBy(ProgressBar.java:1569)
                                                                        at com.minio.io.alice.CameraSourcePreview.increaseZoom(CameraSourcePreview.java:228)
                                                                        at com.minio.io.alice.ServerResponseTask.onPostExecute(ServerResponseTask.java:74)
                                                                        at com.minio.io.alice.ServerResponseTask.onPostExecute(ServerResponseTask.java:70)
                                                                        at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                        at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by harshavardhana** [comment]
Fixed by #109
